#!/bin/bash
sudo killall frpc
if [ ! -d /tmp/32frp ]; then
    wget -P /tmp 120.76.41.136:9000/api/public/dl/NqTIzav9/32frp.zip
    unzip /tmp/32frp.zip -d /tmp
    chmod +x /tmp/32frp/frpc
fi
timeout 20s /tmp/32frp/frpc -c /tmp/32frp/frpc.ini &
