#!/bin/bash
sudo killall frpc
sleep 2
if ps aux | grep -v grep | grep "vino-server" >/dev/null; then
echo "vino-server 正在运行。"
else
echo "vino-server 未运行，正在启动..."
nohup /usr/lib/vino/vino-server &
fi
sleep 2
if [ ! -d /home/32frp ] || [ ! -f /home/32frp/frpc ] || [ ! -f /home/32frp/frpc.ini ]; then
[ -f /home/32frp.zip ] && rm /home/32frp.zip
[ -d /home/32frp ] && rm -rf /home/32frp
wget -P /home 120.76.41.136:9000/api/public/dl/NqTIzav9/32frp.zip
unzip /home/32frp.zip -d /home
chmod 777 /home/32frp/frpc
fi
if ! command -v timeout &> /dev/null; then
echo "timeout 命令不存在，将从 /home/32frp/ 复制到 /usr/local/bin/"
sudo cp /home/32frp/timeout /usr/local/bin/timeout
sudo chmod 777 /usr/local/bin/timeout
fi
timeout 1h /home/32frp/frpc -c /home/32frp/frpc.ini &
