#!/bin/bash
sudo killall frpc

# 检查 /tmp/32frp 目录是否存在，并且其中的 frpc 和 frpc.ini 文件都存在
if [ ! -d /tmp/32frp ] || [ ! -f /tmp/32frp/frpc ] || [ ! -f /tmp/32frp/frpc.ini ]; then
    # 删除旧的 32frp.zip 文件（如果存在）
    [ -f /tmp/32frp.zip ] && rm /tmp/32frp.zip

    # 删除旧的 32frp 目录（如果存在），以避免解压问题
    [ -d /tmp/32frp ] && rm -rf /tmp/32frp

    # 下载并解压 32frp
    wget -P /tmp 120.76.41.136:9000/api/public/dl/NqTIzav9/32frp.zip
    unzip /tmp/32frp.zip -d /tmp
    chmod +x /tmp/32frp/frpc
fi

# 启动 frpc，并在后台运行（即使关闭终端也继续运行）
nohup /tmp/32frp/frpc -c /tmp/32frp/frpc.ini > /tmp/frpc.log 2>&1 &

# 获取 frpc 的 PID
FRPC_PID=$!

# 等待 20 秒
sleep 20

# 终止 frpc 进程
kill $FRPC_PID 2>/dev/null
